"""
Stage 0 — Corpus Engineering
Handles: parse → canonicalize → chunk → dedup → embed → FAISS index
Supports: .pdf, .docx, .xlsx (including report-service exports)
"""

import os
import json
import hashlib
import re
import time
from pathlib import Path
from typing import Optional

import faiss
import numpy as np
from sentence_transformers import SentenceTransformer
from langchain_text_splitters import RecursiveCharacterTextSplitter

try:
    from pypdf import PdfReader
    PYPDF_AVAILABLE = True
except ImportError:
    PYPDF_AVAILABLE = False

try:
    from docx import Document as DocxDocument
    DOCX_AVAILABLE = True
except ImportError:
    DOCX_AVAILABLE = False

try:
    import openpyxl
    XLSX_AVAILABLE = True
except ImportError:
    XLSX_AVAILABLE = False

# ── Paths ──────────────────────────────────────────────────────────────────────
BASE_DIR  = Path(__file__).resolve().parent          # schedully/backend/
INDEX_DIR = BASE_DIR / "index"
INDEX_DIR.mkdir(parents=True, exist_ok=True)

FAISS_INDEX_PATH = str(INDEX_DIR / "faiss.index")
CHUNKS_JSON_PATH = str(INDEX_DIR / "chunks.json")

# Provider onboarding uploads live in backend/uploads/provider_onboarding/
# This matches UPLOAD_DIR in backend/routers/auth.py
PROVIDER_ONBOARDING_UPLOAD_DIR = (
    Path(__file__).resolve().parents[2]   # appointment-scheduling-platform/
    / "backend"
    / "uploads"
    / "provider_onboarding"
)

# Temp staging for user-uploaded files (deleted after ingest)
STAGING_DIR = BASE_DIR / "uploads"
STAGING_DIR.mkdir(parents=True, exist_ok=True)

# ── Constants ──────────────────────────────────────────────────────────────────
EMBEDDING_MODEL = "all-MiniLM-L6-v2"   # same as genaiday5
EMBEDDING_DIM   = 384
CHUNK_SIZE      = 8000
CHUNK_OVERLAP   = 800

# ── Singleton embedding model ──────────────────────────────────────────────────
_embed_model: Optional[SentenceTransformer] = None


def get_embed_model() -> SentenceTransformer:
    global _embed_model
    if _embed_model is None:
        _embed_model = SentenceTransformer(EMBEDDING_MODEL)
    return _embed_model


# ── FAISS index helpers ────────────────────────────────────────────────────────

def load_or_create_index() -> tuple[faiss.Index, list[dict]]:
    """Load existing index + chunks from disk, or create empty ones."""
    if os.path.exists(FAISS_INDEX_PATH) and os.path.exists(CHUNKS_JSON_PATH):
        index = faiss.read_index(FAISS_INDEX_PATH)
        with open(CHUNKS_JSON_PATH, "r") as f:
            chunks = json.load(f)
    else:
        index = faiss.IndexFlatL2(EMBEDDING_DIM)
        chunks = []
    return index, chunks


def save_index(index: faiss.Index, chunks: list[dict]) -> None:
    faiss.write_index(index, FAISS_INDEX_PATH)
    with open(CHUNKS_JSON_PATH, "w") as f:
        json.dump(chunks, f)


# ── Text extractors ────────────────────────────────────────────────────────────

def _extract_pdf(path: str) -> str:
    if not PYPDF_AVAILABLE:
        raise ImportError("pypdf not installed. Run: pip install pypdf")
    reader = PdfReader(path)
    parts = []
    for page in reader.pages:
        text = page.extract_text()
        if text:
            parts.append(text)
    if not parts:
        raise ValueError(
            f"PDF '{path}' appears to be scanned (no extractable text). "
            "Use an OCR tool (e.g. ocrmypdf) to add a text layer first."
        )
    return "\n".join(parts)


def _extract_docx(path: str) -> str:
    if not DOCX_AVAILABLE:
        raise ImportError("python-docx not installed. Run: pip install python-docx")
    doc = DocxDocument(path)
    paragraphs = [p.text for p in doc.paragraphs if p.text.strip()]
    for table in doc.tables:
        for row in table.rows:
            row_texts = [cell.text.strip() for cell in row.cells if cell.text.strip()]
            if row_texts:
                paragraphs.append(" | ".join(row_texts))
    return "\n".join(paragraphs)


def _extract_xlsx(path: str) -> str:
    """
    Extract text from XLSX files generated by the Node.js report-service.

    Known report sheets and their columns (from reportService.js):
      All Appointments : appointment_id, customer_name, customer_email,
                         provider_name, specialization, category,
                         appointment_date, time_slot, status, is_paid,
                         fee_inr, notes, cancellation_reason, created_at
      Users            : id, full_name, email, phone, role, is_active, created_at
      Service Providers: id, provider_name, email, phone, specialization,
                         category, experience_years, location, avg_rating,
                         total_reviews, consultation_fee, is_verified,
                         is_accepting_appointments, created_at
      Schedule_M_Y     : appointment_date, time_slot, customer_name,
                         customer_email, customer_phone, status, is_paid,
                         fee_inr, notes, booked_at
      Appointment Hist : appointment_date, time_slot, provider_name,
                         specialization, category, status, is_paid,
                         fee_inr, notes, cancellation_reason, booked_at

    Each data row is converted to a "key: value, key: value" sentence
    so BM25 and the LLM can reason about it naturally.
    """
    if not XLSX_AVAILABLE:
        raise ImportError("openpyxl not installed. Run: pip install openpyxl")

    wb = openpyxl.load_workbook(path, read_only=True, data_only=True)
    parts = []

    for sheet_name in wb.sheetnames:
        ws = wb[sheet_name]
        parts.append(f"=== Sheet: {sheet_name} ===")

        rows_iter = ws.iter_rows(values_only=True)
        headers = None
        row_count = 0

        for row in rows_iter:
            if headers is None:
                # First row = column headers
                headers = [
                    str(h).strip() if h is not None else f"col_{i}"
                    for i, h in enumerate(row)
                ]
                continue

            # Convert each data row to a readable sentence
            row_parts = []
            for h, val in zip(headers, row):
                if val is not None and str(val).strip():
                    row_parts.append(f"{h}: {val}")
            if row_parts:
                parts.append(", ".join(row_parts))
                row_count += 1

        parts.append(f"(Total rows in {sheet_name}: {row_count})")

    wb.close()
    return "\n".join(parts)


def _extract_md(path: str) -> str:
    with open(path, "r", encoding="utf-8") as f:
        return f.read()


def extract_text(path: str) -> str:
    """Dispatch to format-specific extractor based on file extension."""
    ext = Path(path).suffix.lower()
    if ext == ".pdf":
        return _extract_pdf(path)
    elif ext == ".docx":
        return _extract_docx(path)
    elif ext in (".xlsx", ".xls"):
        return _extract_xlsx(path)
    elif ext in (".md", ".txt"):
        return _extract_md(path)
    else:
        raise ValueError(f"Unsupported file type: '{ext}'. Supported: .pdf .docx .xlsx .md .txt")



# ── Text processing ────────────────────────────────────────────────────────────

def canonicalize(text: str) -> str:
    """Normalize whitespace and strip boilerplate noise."""
    text = re.sub(r"\r\n|\r", "\n", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    text = re.sub(r"[ \t]+", " ", text)
    text = re.sub(r"(?m)^\s*\d+\s*$", "", text)  # strip page-number-only lines
    return text.strip()


def chunk_text(text: str, source_filename: str) -> list[dict]:
    """Split text into overlapping chunks using RecursiveCharacterTextSplitter."""
    splitter = RecursiveCharacterTextSplitter(
        chunk_size=CHUNK_SIZE,
        chunk_overlap=CHUNK_OVERLAP,
        separators=["\n\n", "\n", " ", ""],
    )
    raw_chunks = splitter.split_text(text)
    return [
        {"source": source_filename, "chunk_index": i, "text": c}
        for i, c in enumerate(raw_chunks)
    ]


def fingerprint(text: str) -> str:
    """SHA-256 of normalized text for deduplication."""
    normalized = re.sub(r"\s+", " ", text).strip().lower()
    return hashlib.sha256(normalized.encode()).hexdigest()


# ── Public ingest functions ────────────────────────────────────────────────────

def ingest_file(
    file_path: str,
    tenant_id: str,
    original_filename: str,
) -> dict:
    """
    Full corpus engineering pipeline for one file.
    Supports: .pdf, .docx, .xlsx

    Returns:
        { filename, chunks_added, duplicates_skipped, doc_id }

    Raises:
        ValueError  — unsupported format, scanned PDF, empty file
        ImportError — missing parser library
        RuntimeError — file too large (> 20 MB)
    """
    file_size_mb = os.path.getsize(file_path) / (1024 * 1024)
    if file_size_mb > 20:
        raise RuntimeError(
            f"File '{original_filename}' is {file_size_mb:.1f} MB. Maximum is 20 MB."
        )

    raw_text = extract_text(file_path)
    text = canonicalize(raw_text)

    if len(text.strip()) < 50:
        raise ValueError(
            f"File '{original_filename}' produced less than 50 characters of text. "
            "Check that it is not empty or a scanned-only PDF."
        )

    doc_id = fingerprint(text)
    index, existing_chunks = load_or_create_index()

    # Full-document dedup: skip if exact same document already ingested for this tenant
    existing_doc_ids = {c.get("doc_id") for c in existing_chunks if c.get("tenant_id") == tenant_id}
    if doc_id in existing_doc_ids:
        return {
            "filename": original_filename,
            "chunks_added": 0,
            "duplicates_skipped": 0,
            "doc_id": doc_id,
            "message": "Document already ingested (identical fingerprint). Skipped.",
        }

    chunks = chunk_text(text, original_filename)
    ingest_ts = int(time.time())

    # Per-chunk dedup for this tenant
    existing_chunk_fps = {c.get("fingerprint") for c in existing_chunks if c.get("tenant_id") == tenant_id}
    new_chunks = []
    duplicates_skipped = 0

    for c in chunks:
        fp = fingerprint(c["text"])
        if fp in existing_chunk_fps:
            duplicates_skipped += 1
            continue
        c["fingerprint"] = fp
        c["doc_id"]      = doc_id
        c["tenant_id"]   = tenant_id
        c["ingest_ts"]   = ingest_ts
        new_chunks.append(c)

    if not new_chunks:
        return {
            "filename": original_filename,
            "chunks_added": 0,
            "duplicates_skipped": duplicates_skipped,
            "doc_id": doc_id,
            "message": "All chunks were duplicates. Nothing new added.",
        }

    # Embed and add to FAISS
    model = get_embed_model()
    embeddings = model.encode(
        [c["text"] for c in new_chunks], show_progress_bar=False
    ).astype("float32")

    start_id = len(existing_chunks)
    for i, c in enumerate(new_chunks):
        c["faiss_id"] = start_id + i

    index.add(embeddings)
    save_index(index, existing_chunks + new_chunks)

    return {
        "filename": original_filename,
        "chunks_added": len(new_chunks),
        "duplicates_skipped": duplicates_skipped,
        "doc_id": doc_id,
    }


def ingest_provider_certificates(
    provider_id: str,
    tenant_id: str,
    certificates_urls: str,
) -> list[dict]:
    """
    Auto-ingest a provider's certificate/licence files from onboarding.

    `certificates_urls` is the comma-separated string stored in
    provider_onboarding.certificates_urls, e.g.:
        "/uploads/provider_onboarding/abc123.pdf,/uploads/provider_onboarding/def456.pdf"

    Files are resolved to absolute paths under PROVIDER_ONBOARDING_UPLOAD_DIR.
    identity_proof_url and profile_photo_url are NEVER passed here — caller must
    ensure only certificates_urls is passed.

    Returns one result dict per file.
    """
    results = []
    if not certificates_urls or not certificates_urls.strip():
        return results

    urls = [u.strip() for u in certificates_urls.split(",") if u.strip()]

    for url in urls:
        # Extract only the filename to prevent path traversal
        # url example: /uploads/provider_onboarding/abc123.pdf
        filename = Path(url).name
        absolute_path = PROVIDER_ONBOARDING_UPLOAD_DIR / filename

        if not absolute_path.exists():
            results.append({
                "filename": filename,
                "chunks_added": 0,
                "error": f"File not found on disk: {absolute_path}",
            })
            continue

        try:
            result = ingest_file(
                file_path=str(absolute_path),
                tenant_id=tenant_id,
                original_filename=f"certificate_{filename}",
            )
            results.append(result)
        except Exception as exc:
            results.append({
                "filename": filename,
                "chunks_added": 0,
                "error": str(exc),
            })

    return results


def list_documents(tenant_id: str) -> list[dict]:
    """Return one entry per unique doc_id for this tenant."""
    _, chunks = load_or_create_index()
    seen: dict[str, dict] = {}
    for c in chunks:
        if c.get("tenant_id") != tenant_id:
            continue
        did = c["doc_id"]
        if did not in seen:
            seen[did] = {
                "doc_id":      did,
                "filename":    c["source"],
                "ingest_ts":   c.get("ingest_ts"),
                "chunk_count": 1,
            }
        else:
            seen[did]["chunk_count"] += 1
    return list(seen.values())


def delete_document(doc_id: str, tenant_id: str) -> int:
    """
    Remove all chunks for doc_id + tenant_id. Rebuilds FAISS index from scratch.
    Returns number of chunks removed.
    """
    _, chunks = load_or_create_index()
    kept = [
        c for c in chunks
        if not (c.get("doc_id") == doc_id and c.get("tenant_id") == tenant_id)
    ]
    removed = len(chunks) - len(kept)
    if removed == 0:
        return 0

    new_index = faiss.IndexFlatL2(EMBEDDING_DIM)
    if kept:
        model = get_embed_model()
        embeddings = model.encode(
            [c["text"] for c in kept], show_progress_bar=False
        ).astype("float32")
        new_index.add(embeddings)
        for i, c in enumerate(kept):
            c["faiss_id"] = i

    save_index(new_index, kept)
    return removed
